// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: enspb/ens.proto

package enspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAddressesRequest) Reset() {
	*x = ResolveAddressesRequest{}
	mi := &file_enspb_ens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAddressesRequest) ProtoMessage() {}

func (x *ResolveAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enspb_ens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAddressesRequest.ProtoReflect.Descriptor instead.
func (*ResolveAddressesRequest) Descriptor() ([]byte, []int) {
	return file_enspb_ens_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveAddressesRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type ResolveDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDomainsRequest) Reset() {
	*x = ResolveDomainsRequest{}
	mi := &file_enspb_ens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDomainsRequest) ProtoMessage() {}

func (x *ResolveDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enspb_ens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDomainsRequest.ProtoReflect.Descriptor instead.
func (*ResolveDomainsRequest) Descriptor() ([]byte, []int) {
	return file_enspb_ens_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveDomainsRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnsName       string                 `protobuf:"bytes,1,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_enspb_ens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_enspb_ens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_enspb_ens_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_enspb_ens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enspb_ens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_enspb_ens_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type ResolveAllDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAllDomainsRequest) Reset() {
	*x = ResolveAllDomainsRequest{}
	mi := &file_enspb_ens_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAllDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAllDomainsRequest) ProtoMessage() {}

func (x *ResolveAllDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enspb_ens_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAllDomainsRequest.ProtoReflect.Descriptor instead.
func (*ResolveAllDomainsRequest) Descriptor() ([]byte, []int) {
	return file_enspb_ens_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveAllDomainsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ResolveAllDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAllDomainsResponse) Reset() {
	*x = ResolveAllDomainsResponse{}
	mi := &file_enspb_ens_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAllDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAllDomainsResponse) ProtoMessage() {}

func (x *ResolveAllDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enspb_ens_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAllDomainsResponse.ProtoReflect.Descriptor instead.
func (*ResolveAllDomainsResponse) Descriptor() ([]byte, []int) {
	return file_enspb_ens_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveAllDomainsResponse) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

var File_enspb_ens_proto protoreflect.FileDescriptor

const file_enspb_ens_proto_rawDesc = "" +
	"\n" +
	"\x0fenspb/ens.proto\x12\x05enspb\"3\n" +
	"\x17ResolveAddressesRequest\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\"5\n" +
	"\x15ResolveDomainsRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\">\n" +
	"\aAddress\x12\x19\n" +
	"\bens_name\x18\x01 \x01(\tR\aensName\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"?\n" +
	"\x0fResolveResponse\x12,\n" +
	"\taddresses\x18\x01 \x03(\v2\x0e.enspb.AddressR\taddresses\"4\n" +
	"\x18ResolveAllDomainsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"5\n" +
	"\x19ResolveAllDomainsResponse\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains2\xf1\x01\n" +
	"\x03Ens\x12J\n" +
	"\x10ResolveAddresses\x12\x1e.enspb.ResolveAddressesRequest\x1a\x16.enspb.ResolveResponse\x12F\n" +
	"\x0eResolveDomains\x12\x1c.enspb.ResolveDomainsRequest\x1a\x16.enspb.ResolveResponse\x12V\n" +
	"\x11ResolveAllDomains\x12\x1f.enspb.ResolveAllDomainsRequest\x1a .enspb.ResolveAllDomainsResponseB\n" +
	"Z\b./;enspbb\x06proto3"

var (
	file_enspb_ens_proto_rawDescOnce sync.Once
	file_enspb_ens_proto_rawDescData []byte
)

func file_enspb_ens_proto_rawDescGZIP() []byte {
	file_enspb_ens_proto_rawDescOnce.Do(func() {
		file_enspb_ens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enspb_ens_proto_rawDesc), len(file_enspb_ens_proto_rawDesc)))
	})
	return file_enspb_ens_proto_rawDescData
}

var file_enspb_ens_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_enspb_ens_proto_goTypes = []any{
	(*ResolveAddressesRequest)(nil),   // 0: enspb.ResolveAddressesRequest
	(*ResolveDomainsRequest)(nil),     // 1: enspb.ResolveDomainsRequest
	(*Address)(nil),                   // 2: enspb.Address
	(*ResolveResponse)(nil),           // 3: enspb.ResolveResponse
	(*ResolveAllDomainsRequest)(nil),  // 4: enspb.ResolveAllDomainsRequest
	(*ResolveAllDomainsResponse)(nil), // 5: enspb.ResolveAllDomainsResponse
}
var file_enspb_ens_proto_depIdxs = []int32{
	2, // 0: enspb.ResolveResponse.addresses:type_name -> enspb.Address
	0, // 1: enspb.Ens.ResolveAddresses:input_type -> enspb.ResolveAddressesRequest
	1, // 2: enspb.Ens.ResolveDomains:input_type -> enspb.ResolveDomainsRequest
	4, // 3: enspb.Ens.ResolveAllDomains:input_type -> enspb.ResolveAllDomainsRequest
	3, // 4: enspb.Ens.ResolveAddresses:output_type -> enspb.ResolveResponse
	3, // 5: enspb.Ens.ResolveDomains:output_type -> enspb.ResolveResponse
	5, // 6: enspb.Ens.ResolveAllDomains:output_type -> enspb.ResolveAllDomainsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enspb_ens_proto_init() }
func file_enspb_ens_proto_init() {
	if File_enspb_ens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enspb_ens_proto_rawDesc), len(file_enspb_ens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enspb_ens_proto_goTypes,
		DependencyIndexes: file_enspb_ens_proto_depIdxs,
		MessageInfos:      file_enspb_ens_proto_msgTypes,
	}.Build()
	File_enspb_ens_proto = out.File
	file_enspb_ens_proto_goTypes = nil
	file_enspb_ens_proto_depIdxs = nil
}
